add celery, redis, simple-jwt, registration with email
RazieL-hub/support_ticket pull request #6
Opened 2021-09-07 15:52 UTC by RazieL-hub

add celery, redis, simple-jwt, registration with email

2021-09-07 17:07 UTC, Niccolum requested changes

2021-09-07 17:07 UTC, Niccolum commented on Support/Dockerfile
> +ENV PYTHONDONTWRITEBYTECODE 1
В чём смысл конкретно этой переменной среды здесь?

2021-09-07 17:07 UTC, Niccolum commented on Support/Dockerfile
> +#RUN apk update \
Не храни комменты, удали, если сейчас не нужно.

2021-09-07 17:07 UTC, Niccolum commented on Support/Makefile
> +	docker exec -it ${WEB_CONTAINER_NAME} python manage.py makemigrations
У тебя все команды юзают напрямую докер. Почему не композ?

2021-09-07 17:07 UTC, Niccolum commented on Support/Makefile
> +POSTGRES_CONTAINER_NAME=podpisby2_postgres
Не проще ли это хранить в переменных среды, а остальное отдать на растерзание композу?

2021-09-07 17:07 UTC, Niccolum commented on Support/authentication/serializers.py
> +        email = attrs.get('email', '')
Зачем?

2021-09-07 17:07 UTC, Niccolum commented on Support/authentication/views.py
> +        print(dir(serializer))
Принты в коде. Принты в коде

2021-09-07 17:07 UTC, Niccolum commented on Support/config/settings.py
> +ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")
Поставь значение по умолчанию, иначе будет ошибка, если такой переменной среды не будет задано.

2021-09-07 17:07 UTC, Niccolum commented on Support/config/settings.py
> +    'rest_framework_simplejwt',
Ты уверен, что нужно использовать одновременно его с djoser?

2021-09-07 17:07 UTC, Niccolum commented on Support/config/settings.py
> +        'HOST': 'postgres',
Ошибка, если запускать локально. Сделай через переменную среды

2021-09-07 17:07 UTC, Niccolum commented on Support/config/settings.py
> +CELERY_BROKER_URL = 'redis://redis:6379/0'
Ошибка, если запускать локально.

2021-09-07 17:07 UTC, Niccolum commented on Support/config/settings.py
> +CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
Ошибка, если запускать локально.

2021-09-07 17:07 UTC, Niccolum commented on Support/docker-compose.yml
> +    environment:
Лучше подкрепить и тут файл с переменными среды, в котором они будут заданы. Чтобы задавать их в одном месте для контейнера с приложением и базой

2021-09-07 17:07 UTC, Niccolum commented on Support/docker-compose.yml
> +    env_file:
Через environment можешь дополнительно переопределить нужные переменные среды, которые отличаются от запуска локально.

2021-09-08 06:31 UTC, RazieL-hub commented on Support/Dockerfile
> +ENV PYTHONDONTWRITEBYTECODE 1
PYTHONUNBUFFERED гарантирует, что наш вывод консоли выглядит знакомым и не буферизируется Docker, что нам не нужно. PYTHONDONTWRITEBYTECODE означает, что Python не будет пытаться создавать файлы .pyc, которые мы также не желаем.

2021-09-08 06:32 UTC, RazieL-hub commented on Support/Dockerfile
> +#RUN apk update \
удалил комент

2021-09-08 06:33 UTC, RazieL-hub commented on Support/Makefile
> +	docker exec -it ${WEB_CONTAINER_NAME} python manage.py makemigrations
попробую поюзать на docker-compose

2021-09-08 06:33 UTC, RazieL-hub commented on Support/Makefile
> +POSTGRES_CONTAINER_NAME=podpisby2_postgres
это вообще удалиться :)

2021-09-08 06:34 UTC, RazieL-hub commented on Support/Makefile
> +	docker exec -it ${WEB_CONTAINER_NAME} python manage.py makemigrations
raziel@raziel:~/Django projects/Support/Support$ docker-compose exec web python manage.py migrate --noinput
Operations to perform:
  Apply all migrations: admin, auth, authentication, contenttypes, sessions, taskmanager
Running migrations:
  No migrations to apply.

2021-09-08 06:35 UTC, RazieL-hub commented on Support/authentication/serializers.py
> +        email = attrs.get('email', '')
убрал, так как думал, что прямо там сделаю отправку на почту.

2021-09-08 06:36 UTC, RazieL-hub commented on Support/config/settings.py
> +        'HOST': 'postgres',
если поставить localhost или 127.0.0.1 не запускается в docker-compose

2021-09-08 06:36 UTC, RazieL-hub commented on Support/config/settings.py
> +CELERY_BROKER_URL = 'redis://redis:6379/0'
та же самая проблема.

2021-09-08 06:36 UTC, RazieL-hub commented on Support/config/settings.py
> +CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
та же самая проблема.

2021-09-08 13:13 UTC, Niccolum commented on Support/Dockerfile
> +ENV PYTHONDONTWRITEBYTECODE 1
Первое - ок. Второе -, наоборот желательно, т.к. .pyc исполняется быстрее. Для нас важно, чтобы байт-код не попадал в гит

2021-09-08 13:16 UTC, Niccolum commented on Support/config/settings.py
> +        'HOST': 'postgres',
Смысл в том, чтобы в файлике с переменными среды были данные, чтобы запускать локально, а в композе через environment переопределять некоторые переменные среды, например - redis вместо localhost, чтобы это работало уже внутри самого композа. Так или иначе не все 100% времени желательно запускать приложение через композ, оставить возможность запустить его локально.

2021-09-08 13:17 UTC, Niccolum commented on Support/config/settings.py
> +CELERY_BROKER_URL = 'redis://redis:6379/0'
Торт же самый ответ

2021-09-08 13:17 UTC, Niccolum commented on Support/config/settings.py
> +CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
Тот же самый ответ

2021-09-08 13:18 UTC, Niccolum requested changes

2021-09-08 13:18 UTC, Niccolum commented on Support/Makefile
> +	docker exec -it ${WEB_CONTAINER_NAME} python manage.py makemigrations
Да, выглядит как то, что нужно

2021-09-08 13:27 UTC, merged