Develop
RazieL-hub/support_ticket pull request #7
Opened 2021-09-13 13:16 UTC by RazieL-hub

dell comments, add .env, dell unused imports

2021-09-14 06:48 UTC, Niccolum requested changes

2021-09-14 06:48 UTC, Niccolum commented on Support/authentication/views.py
> +        send_activation_email.delay(email_subject, email_body, os.getenv('EMAIL_HOST_USER'),
1. А нужно ли явно передавать EMAIL_HOST_USER? Мб подставлять его внутри?
2. Если всё таки нужно подставлять явно, то сохраняй его в настройках и получай из from django.conf import settings

2021-09-14 06:48 UTC, Niccolum commented on Support/authentication/views.py
> +            payload = jwt.decode(token, os.getenv('SECRET_KEY'))
Secret_key лучше получать явно из настроек
Сейчас у тебя конфиг по факту размазан по всему коду. Если вдруг что поменяется (имя переменной среды, к примеру) или какая логика, с ним связанная, придётся искать по всему коду и думать исправить или нет.

2021-09-14 06:48 UTC, Niccolum commented on Support/authentication/views.py
> +            user = User.objects.get(id=payload['user_id'])
Нет обработки ошибки на несуществующего юзера

2021-09-14 06:48 UTC, Niccolum commented on Support/taskmanager/views.py
> +    permission_classes = (AllowAny, )
Почему список ответов видят все?

2021-09-14 15:40 UTC, RazieL-hub commented on Support/taskmanager/views.py
> +    permission_classes = (AllowAny, )
я с пермишинами балуюсь пока больше.

2021-09-14 15:47 UTC, RazieL-hub commented on Support/authentication/views.py
> +            user = User.objects.get(id=payload['user_id'])
Код пока вообще удалю

2021-09-14 15:47 UTC, RazieL-hub commented on Support/authentication/views.py
> +            user = User.objects.get(id=payload['user_id'])
он вообще пока не работает.

2021-09-14 17:00 UTC, Niccolum requested changes

2021-09-14 17:00 UTC, Niccolum commented on Support/taskmanager/views.py
> +    queryset = Ticket.objects.filter()
Что за пустой filter?

2021-09-14 17:02 UTC, RazieL-hub commented on Support/taskmanager/views.py
> +    queryset = Ticket.objects.filter()
ну так, как явный pk  я не передаю, он берёт автоматом.

2021-09-15 07:06 UTC, RazieL-hub commented on Support/authentication/views.py
> +        send_activation_email.delay(email_subject, email_body, os.getenv('EMAIL_HOST_USER'),
ИСПРАВЛЕНО

2021-09-15 07:07 UTC, RazieL-hub commented on Support/authentication/views.py
> +            payload = jwt.decode(token, os.getenv('SECRET_KEY'))
ИСПРАВЛЕНО

2021-09-15 07:07 UTC, RazieL-hub commented on Support/authentication/views.py
> +            user = User.objects.get(id=payload['user_id'])
Этот код хочу оставить для базы, потом допилить.

2021-09-15 07:07 UTC, RazieL-hub commented on Support/taskmanager/views.py
> +    queryset = Ticket.objects.filter()
ИСПРАВЛЕНО

2021-09-15 07:23 UTC, merged